### PR TITLE
Improve the User->age()

### PR DESCRIPTION
**Pull request by NicolasCARPi**
* use early return
* simplify the logic
* remove whitespaces

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Also, I would HIGHLY recommend using type annotations. They make the code so much better!

**Comment by wi-wissen** [comment]
Thank you @NicolasCARPi for reviewing this function!

I understand what you did, but I am not sure if it is better than the old version. In my point of view the old one is better to read for beginners.

Type annotations are a good point. I have to admit that I am to lazy for them in all my projects. But feel free to use them.

**Comment by NicolasCARPi** [comment]
> I am not sure if it is better than the old version

It's always best to avoid `else`.

>  In my point of view the old one is better to read for beginners.

It is in fact the contrary. Look: to know what happens if the birthday is null, you have to scroll down to the end of the function to find it returns 'unknown', the action is far from the condition. Also, if your code is supposed to be read by beginners, why not have good quality code from the start?

See: [else is never necessary](https://phpmd.org/rules/cleancode.html#elseexpression) from PHPMD.

But at the end of the day, you do what you think is best, it's your project ;) I'm just trying to show you another way to write code, but all of this is subjective, there is no "better" way, just different. I would agree with you that it would be less readable if we were to use ternary operators, but this is not the case, here the function body is shorter AND more readable (IMHO).

**Comment by NicolasCARPi** [comment]
FYI: https://freek.dev/1593-writer-readable-php-avoid-indentation-by-returning-early ;)

**Pull request merged**
